In [1]:
import numpy as np

In [44]:
a = np.ones((16, 1))
b = np.arange(3920).reshape((16, 245))

In [55]:
a.dtype
b.dtype

dtype('int64')

In [57]:
c = np.hstack((a,b))
c.dtype

dtype('float64')

In [47]:
import pandas as pd

In [48]:
df = pd.DataFrame(b)

In [49]:
df

,0,1,2,3,4,5,6,7,8,9,...,235,236,237,238,239,240,241,242,243,244
0,0,1,2,3,4,5,6,7,8,9,...,235,236,237,238,239,240,241,242,243,244
1,245,246,247,248,249,250,251,252,253,254,...,480,481,482,483,484,485,486,487,488,489
2,490,491,492,493,494,495,496,497,498,499,...,725,726,727,728,729,730,731,732,733,734
3,735,736,737,738,739,740,741,742,743,744,...,970,971,972,973,974,975,976,977,978,979
4,980,981,982,983,984,985,986,987,988,989,...,1215,1216,1217,1218,1219,1220,1221,1222,1223,1224
5,1225,1226,1227,1228,1229,1230,1231,1232,1233,1234,...,1460,1461,1462,1463,1464,1465,1466,1467,1468,1469
6,1470,1471,1472,1473,1474,1475,1476,1477,1478,1479,...,1705,1706,1707,1708,1709,1710,1711,1712,1713,1714
7,1715,1716,1717,1718,1719,1720,1721,1722,1723,1724,...,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959
8,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2195,2196,2197,2198,2199,2200,2201,2202,2203,2204
9,2205,2206,2207,2208,2209,2210,2211,2212,2213,2214,...,2440,2441,2442,2443,2444,2445,2446,2447,2448,2449
10,2450,2451,2452,2453,2454,2455,2456,2457,2458,2459,...,2685,2686,2687,2688,2689,2690,2691,2692,2693,2694
11,2695,2696,2697,2698,2699,2700,2701,2702,2703,2704,...,2930,2931,2932,2933,2934,2935,2936,2937,2938,2939
12,2940,2941,2942,2943,2944,2945,2946,2947,2948,2949,...,3175,3176,3177,3178,3179,3180,3181,3182,3183,3184
13,3185,3186,3187,3188,3189,3190,3191,3192,3193,3194,...,3420,3421,3422,3423,3424,3425,3426,3427,3428,3429
14,3430,3431,3432,3433,3434,3435,3436,3437,3438,3439,...,3665,3666,3667,3668,3669,3670,3671,3672,3673,3674
15,3675,3676,3677,3678,3679,3680,3681,3682,3683,3684,...,3910,3911,3912,3913,3914,3915,3916,3917,3918,3919

In [50]:
df_two = pd.DataFrame(np.hstack((a,b)))

In [51]:
df_two

,0,1,2,3,4,5,6,7,8,9,...,236,237,238,239,240,241,242,243,244,245
0,1.0,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,...,235.0,236.0,237.0,238.0,239.0,240.0,241.0,242.0,243.0,244.0
1,1.0,245.0,246.0,247.0,248.0,249.0,250.0,251.0,252.0,253.0,...,480.0,481.0,482.0,483.0,484.0,485.0,486.0,487.0,488.0,489.0
2,1.0,490.0,491.0,492.0,493.0,494.0,495.0,496.0,497.0,498.0,...,725.0,726.0,727.0,728.0,729.0,730.0,731.0,732.0,733.0,734.0
3,1.0,735.0,736.0,737.0,738.0,739.0,740.0,741.0,742.0,743.0,...,970.0,971.0,972.0,973.0,974.0,975.0,976.0,977.0,978.0,979.0
4,1.0,980.0,981.0,982.0,983.0,984.0,985.0,986.0,987.0,988.0,...,1215.0,1216.0,1217.0,1218.0,1219.0,1220.0,1221.0,1222.0,1223.0,1224.0
5,1.0,1225.0,1226.0,1227.0,1228.0,1229.0,1230.0,1231.0,1232.0,1233.0,...,1460.0,1461.0,1462.0,1463.0,1464.0,1465.0,1466.0,1467.0,1468.0,1469.0
6,1.0,1470.0,1471.0,1472.0,1473.0,1474.0,1475.0,1476.0,1477.0,1478.0,...,1705.0,1706.0,1707.0,1708.0,1709.0,1710.0,1711.0,1712.0,1713.0,1714.0
7,1.0,1715.0,1716.0,1717.0,1718.0,1719.0,1720.0,1721.0,1722.0,1723.0,...,1950.0,1951.0,1952.0,1953.0,1954.0,1955.0,1956.0,1957.0,1958.0,1959.0
8,1.0,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,1966.0,1967.0,1968.0,...,2195.0,2196.0,2197.0,2198.0,2199.0,2200.0,2201.0,2202.0,2203.0,2204.0
9,1.0,2205.0,2206.0,2207.0,2208.0,2209.0,2210.0,2211.0,2212.0,2213.0,...,2440.0,2441.0,2442.0,2443.0,2444.0,2445.0,2446.0,2447.0,2448.0,2449.0
10,1.0,2450.0,2451.0,2452.0,2453.0,2454.0,2455.0,2456.0,2457.0,2458.0,...,2685.0,2686.0,2687.0,2688.0,2689.0,2690.0,2691.0,2692.0,2693.0,2694.0
11,1.0,2695.0,2696.0,2697.0,2698.0,2699.0,2700.0,2701.0,2702.0,2703.0,...,2930.0,2931.0,2932.0,2933.0,2934.0,2935.0,2936.0,2937.0,2938.0,2939.0
12,1.0,2940.0,2941.0,2942.0,2943.0,2944.0,2945.0,2946.0,2947.0,2948.0,...,3175.0,3176.0,3177.0,3178.0,3179.0,3180.0,3181.0,3182.0,3183.0,3184.0
13,1.0,3185.0,3186.0,3187.0,3188.0,3189.0,3190.0,3191.0,3192.0,3193.0,...,3420.0,3421.0,3422.0,3423.0,3424.0,3425.0,3426.0,3427.0,3428.0,3429.0
14,1.0,3430.0,3431.0,3432.0,3433.0,3434.0,3435.0,3436.0,3437.0,3438.0,...,3665.0,3666.0,3667.0,3668.0,3669.0,3670.0,3671.0,3672.0,3673.0,3674.0
15,1.0,3675.0,3676.0,3677.0,3678.0,3679.0,3680.0,3681.0,3682.0,3683.0,...,3910.0,3911.0,3912.0,3913.0,3914.0,3915.0,3916.0,3917.0,3918.0,3919.0